---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      box: chef-intermediate

suites:
  - name: default
    run_list:
      - recipe[learnrepo::default]
    verifier:
      inspec_tests:
        - test/recipes
